version: '3.9'


services:
  web:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    # depends_on:
    #   - serviceName




  # gunicorn:
  #   image: hh_migrate
  #   container_name: 'gunicorn'
  #   restart: always
  #   command: /bin/sh -c "python3 -m gunicorn -b 0.0.0.0:80 hh.wsgi --reload"
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - migrate
